### PR TITLE
Replace TV logo with voctocat

### PR DESCRIPTION
**Pull request by blinry**
See #215.

screenshot-2017-03-01_15 54 59

This replaces:

- the favicons, and the apple-touch-icons
- the logo in the header
- the play/pause button ("bigplay") displayed in the center of the mediaplayer when the video is paused

I couldn't figure out what `/vendor/assets/mediaelement/bigplay.fw.png` is used for, and how it should differ from the non-"fw" PNG. Can @manno help explain?

### CODE REVIEW

**Comment by rohieb** [comment]
Hmm, these images look blurry to me: 

* public/apple-touch-icon-precomposed.png 
* public/apple-touch-icon.png 
* public/apple-touch-icon-76x76.png

**Comment by blinry** [comment]
Good catch, @roiheb! I forgot to specify the density when using ImageMagick to convert these. Should be as crisp as those resolutions allow now, I force-updated the branch.

**Comment by rohieb** [comment]
@bilrny yes, it seems for PRs with several pictures it's probably best to look at them again on the GitHub web view ^^

**Comment by MaZderMind** [comment]
That looks really Awsome <3

**Comment by blinry** [comment]
I'm glad you like it! :)

Hm, @manno, could you explain how `/vendor/assets/mediaelement/bigplay.fw.png` and `/vendor/assets/mediaelement/bigplay.png` should be different? (They're the same, currently.)

**Comment by blinry** [comment]
@MaZderMind, if you want to, you can link to https://morr.cc/voctocat/ in the news entry – the SVG & license is there, just in case someone wants to reuse it! :)

**Comment by MaZderMind** [comment]
@blinry gute idee, hab ich geändert.

**Pull request merged**
