### PR TITLE
Improve timelens alignment

### PR DESCRIPTION
**Pull request by katrinleinweber**
Follow-up to #349, because that one didn't contain any CSS update which may be desired for nicer timelens display:

screen shot 2019-01-02 at 11 25 32

In case an event has no subtitle, the timelens is still shifted towards the middle of the thumbnail:

screen shot 2019-01-02 at 11 23 50

I couldn't figure this out during 1h of playing around with various `align`, `position`, `bottom` and `margin` style settings. Hoping these suggestions are still helpful iterations on the way. Please feel free to update them directly in this PR.

### CODE REVIEW

**Comment by MaZderMind** [comment]
the desired placement should be achievable with flexbox-display:
https://stackoverflow.com/a/31002364
https://css-tricks.com/snippets/css/a-guide-to-flexbox/

**Comment by manno** [comment]
Is this ready now ❤️?

**Comment by katrinleinweber** [comment]
No, sorry. I don't have enough CSS experience to convert the entire `event-preview` or `caption` class to nice `flexbox`es. That seems to be necessary based on what I read in resources @MaZderMind referenced.

**Comment by saerdnaer** [comment]
Please reopen, when this PR has been updated.

**Pull request closed without merging**
