### PR TITLE
Use different variants for the play icon (pausing, waving)

### PR DESCRIPTION
**Pull request by blinry**
Removing the circular border makes the voctocat more recognizable. The
light and dark elements make it visible on all surfaces.

Edit by @mazdermind:
Before:
bildschirmfoto 2017-09-26 um 11 53 52

Before Hover:
bildschirmfoto 2017-09-26 um 11 53 54

After:
bildschirmfoto 2017-09-26 um 11 53 45

After Hover:
bildschirmfoto 2017-09-26 um 11 53 49

### CODE REVIEW

**Comment by blinry** [comment]
I think this can also be merged :)

**Comment by MaZderMind** [comment]
@blinry I hope you don't mind me adding screenshots of the before/after state to your PR.

I did like the original style better, but I guess that's a personal preference.

What is problematic in my eyes is the use of the dark-green from the 33C3 Theme, because thi color is kinda' volatile, it will be removed once we updated the header-image to the 34C3 Theme which will then be the header for the next year.

I'd rather not use a congress-theme specific color for something different then the header-image. The universal highlight-color would be the orange (#d87500)

**Comment by blinry** [comment]
Okay, without color, I don't like the "new style" very much, either, so let's keep the old one. But I pushed the following changes to this branch:

- set hovered/unhovered play icons to the same opacity
- when the player is paused, display a voctocat holding a pause sign
- when seeking or buffering, display a waving voctocat

**Comment by blinry** [comment]
What do ya think about this? :)

**Comment by blinry** [comment]
While were at it, wanna merge this one, as well? Need my waving voctocat! <3

**Pull request merged**
