### PR TITLE
Upgrade gems

### PR DESCRIPTION
**Pull request by saerdnaer**
TODOs: 
* [ ] Test elasticsearch, and maybe downgrade it again...

### CODE REVIEW

**Comment by manno** [comment]
@saerdnaer updating all the libraries is often a lot of work. But if you can get the tests green, why not ;)

Not sure you can update the elasticsearch gem, we're depending on an old version, because of our indexing file.

**Comment by manno** [comment]
Why change the release_date to a dateime? I think historically we choose date, because we didn't know the release times for most of the old videos? Wonder if changing that has any side effects, i.e. on the APIs and thirdparty apps?

**Comment by saerdnaer** [comment]
> Why change the release_date to a dateime? I think historically we choose date, because we didn't know the release times for most of the old videos? Wonder if changing that has any side effects, i.e. on the APIs and thirdparty apps?

The sorting was inconsistent, c.f. #343

**Comment by saerdnaer** [comment]
I tried to test everything locally, before deploying master but got following error during search:
image

Which looks like a bug in elasticserach-model c.f.

https://github.com/uken/fluent-plugin-elasticsearch/issues/699#issuecomment-576309527

**Pull request merged**
