### PR TITLE
redesign player & download page

### LINKED ISSUE #64: Revise/redesign player page
Currently the download tab looks similar to this:
temp

the folder in which a recording is stored at might also trigger display of an hd or sd flag simular to the language. Mookup:
temp2

### PR DESCRIPTION
**Pull request by MaZderMind**
WiP PR to make upcoming changes visible and accessable
fixes #64 & #101 

---

# Screenshots from the final Layout:

## Event with multiple Languages and Subtitles-Flag (see #101)
event-with-multiple-languages-and-subtitles-flag

## Event with single Language and multiple Subtitles
event-with-single-language-multiple-subtitles

## Event with single Language and no Subtitles
event-with-single-language

## Event without HQ-Version, WebM, Audio or Filessize-Information
event-without-hq-version-webm-audio-or-size

## Event with Ogg-File without Filesize-Information
event-without-size-with-ogg

### CODE REVIEW

**Comment by MaZderMind** [comment]
This PR is ready for Review now

**Comment by jjeising** [comment]
I really like this! 👍🏻 Would you like to discuss style enhancements here before merging? Might be a better idea to get this online and iterate from there.

**Comment by MaZderMind** [comment]
@jjeising sure, just wanted to get basic feedback from the team, so that we're all on the same level and nobody is surprised ;)

**Comment by MaZderMind** [comment]
Talks with Subtitles now have an additional Improve-Link (which is identical to the Link displayed when not subtitles are Present, just less prominent and with different Wording):

bildschirmfoto 2016-11-15 um 22 25 03

**Comment by jjeising** [comment]
Some suggestions here, mostly related to _real data_ issues.

We should also discuss inactive tab colors and maybe some button colors.

[Annotated page 1](https://cloud.githubusercontent.com/assets/40333/20326369/bc0e3002-ab88-11e6-9c7a-1f0c19c85446.png)
[Annotated page 2](https://cloud.githubusercontent.com/assets/40333/20326370/bc3472ee-ab88-11e6-9471-03779baa3b3d.png)

**Pull request merged**
