### PR TITLE
Optimize Download section + add slides

### PR DESCRIPTION
**Pull request by saerdnaer**
This PR provides basic support to add lecure slides as PDF or (MP4) video to an event.

### CODE REVIEW

**Comment by manno** [comment]
@saerdnaer there is still an issue with `recordings.video` vs. `recordings.slides` regarding mp4 slides. I added a failing test, feel free to change it, I'm not sure which solution is intended :)

**Comment by saerdnaer** [comment]
Actually this behaviour was intended. 
`recordings.slides` is currently only used for the slide download block, `recordings.videos` used by the player and an filtered version of `recordings.slides` is used for the video download block.

AFAIK, the plan for 34C3 is to upload the slides from frab as PDF as well as the actual used slides during the presentation as slides.mp4, with only the original audio track without any translations. The video download tabs only list the files with all languages, so the slides mp4 does not appear there – but the user can select the slide stream as video in the players dropdown.

**Comment by manno** [comment]
So you expect `recordings.videos` to return the slide mp4. Ok, I'll fix the test.

**Comment by saerdnaer** [comment]
Updated screenshot:



The rendering bug regarding the slides mp4 language might be ignored, as afaik slides.mp4 files will only have one audio track.

**Comment by saerdnaer** [comment]
Yes, ready for merge. Sorry for the late reply, was already at Leipzig for buildup.

**Comment by MaZderMind** [comment]
deployed

**Pull request merged**
