### PR TITLE
redesign startpage

### LINKED ISSUE #74: Umbau Recent-Videos/-Events
## To be discussed.

**Ideen:**
Recent Events ->
- auf die Startseite
- Titel anzeigen
- 2-3 Recordings auflisten (Anzahl in Klammer)

News nur anzeigen wenn neuste News <14 Tage alt
Recent Recordings -> unter "Recent Videos" anzeigen

### PR DESCRIPTION
**Pull request by MaZderMind**
fixes #74

### CODE REVIEW

**Comment by MaZderMind** [comment]
First Draft screens:

---
# Desktop
desktop

---
# iPad Landscape
ipad-landscape

---
# iPad Portrait
ipad-portrait

---
# iPhone Portrait
iphone-landscape

---
# iPhone Portrait
iphone-portrait

**Comment by MaZderMind** [comment]
@manno I merged your branch into this one and extended the migration. The scopes now use the new column. Would you mind reviewing the rails related changes?

**Comment by jjeising** [comment]
Thanks for the implementation! I really like the search bar, gathered some additional ideas here:

[Front page full width comments](https://cloud.githubusercontent.com/assets/40333/20819860/7db3df08-b837-11e6-98bd-038c1c9ad2f1.png)

I'll try to provide an alternative header background image.

**Comment by MaZderMind** [comment]
@jjeising thank you much for your comments. I'll see what I can do and come back to you with updated screenshots.

**Comment by MaZderMind** [comment]
@jjeising here are my responses to your and the changes I implemented:
- Promoted events are missing context, bluisch background does not fit layout, paging bullets are somehow wrong -> will be handled in #147 because it needs more design input (ie a new background image) and is not part of the structural changes in this PR
- Search-Button is left and unexpected there: Actually it is not a button either. I moved it to the right and made it a submit-button.
- Wording talks, adding of files to the tagline: Most of them are talks. The Backend-Terminology is "events" but this word is quite ambiguous. We could call them Videos, because to the uninitiated "one video" might more relate to one logical recorded event, not to a release. I'll change the word to video for the time being. The file-count is not strictly necessary nor of any use to people outside of the VOC, but i find it a pretty impressive number and as our visitors are probably somehow technical, i'd keep it just for marketing purposes. 
- Distribution-Buttons have been moved closer to the search-bar
- The two-lines-headlines in the recently-view are now limited to one line and overflow with an ellipsis.
- The Thumbs are now smaller and the date is less prominent. The title is bigger in font-size.
- The more-links now have better clustering with a line above them
- Line-Height of the news is simehow expected. Every line in the news is its own paragraph, so this is more a content-problem and probably related to #148

bildschirmfoto 2016-12-08 um 13 35 42

bildschirmfoto 2016-12-08 um 13 30 20

**Comment by jjeising** [comment]
Looks good to me!

**Pull request merged**
